version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mobile-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mobile
      MYSQL_USER: master
      MYSQL_PASSWORD: master
    ports:
      - "3306:3306"
    volumes:
      - ./dump/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    container_name: mobile-core
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mobile?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: master
